### ISSUE TITLE
cannot install package via composer, getting this error all the time

### ISSUE THREAD

**Issue by virtuman** [magento-hackathon/E-MailPreview#11]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento-hackathon/e-mail-preview could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by Schrank** [comment]
composer only installs stable version by default. This means you have to set an unstable version, e.g. `dev-<branch>`, in this case: `dev-master`.

If you want to be sure, to stay with a specific "version", you can specify a commit: `dev-master#<hashofcommit>`: `dev-master#5844e58526a79879d3e10aca28dc6901eb7c542d` for the latestet
