### ISSUE TITLE
Tiny mce editor is not showing

### ISSUE THREAD

**Issue by mopheus** [magento-hackathon/E-MailPreview#12]
Hello Matthias,
thanks for the good and free extention...
But I had only one problem...when I use your extention with this tiny mce extention:
http://urthemes.com/magento-extensions/magento-wysiwyg-editor-for-transactional-emails.html

They don´t show the editor...did you have a solution ?

Thanks for your help...
mopheus

**Comment by mzeis** [comment]
Hi, 

thanks for using our extension! We didn't test it with the TinyMCE extension you mentioned and I never used it so I would have to have a closer look.

Which Magento version do you use?

Matthias

**Comment by mopheus** [comment]
Hi Matthias,

thanks for your reply…I use magento  1.9.1.

Thanks for support……..

Markus Marcel


Gesendet: Sonntag, 8. Februar 2015 21:12
An: magento-hackathon/E-MailPreview
Cc: NET2SELL | Markus Marcel Ifenthaler
Betreff: Re: [E-MailPreview] Tiny mce editor is not showing (#12)


Hi,

thanks for using our extension! We didn't test it with the TinyMCE extension you mentioned and I never used it so I would have to have a closer look.

Which Magento version do you use?

Matthias

**Comment by mzeis** [comment]
I had a look at our extension and concluded that tackling this problem would have to be part of a bigger facelift.

I can't make promises on when and if we'll do a refactoring of this extension. We developed this as a weekend project at the hackathon back when 1.7.0.2 was the current release and the extension shows its age. For me it doesn't work properly in its current state and to be honest I'm not using it in my day-to-day work.

@tobihille and @mpaepper: any opinions on this?

**Comment by mopheus** [comment]
Bitte verwenden Sie unsere neue EMAIL Adresse : ifenthaler@net2sell.de

Danke

**Comment by mpaepper** [comment]
I agree with Matthias!

I do not use the extension regularly and do not see a big benefit of a
refactoring for TinyMCE.

But if you want to work on it, a pull request is very welcome :)


<http://www.magentocommerce.com/certification/directory/dev/47773/>

--
Marc Päpper - M.Sc. Neuro-Cognitive Psychology, B.Sc. Informatik
Programmierung und IT-Projektmanagement
www.lemundo.de

Lemundo GmbH
Lerchenstraße 28
22767 Hamburg

Tel.: +49-(0)40-28780924

Rechtsform: GmbH
Unternehmenssitz: Hamburg
Handelsregister beim Amtsgericht: Hamburg
Handelsregister-Nummer: HRB 123272
Geschäftsführer: Marcus Creutzmann, Philip Günther, Marc Päpper

2015-03-05 21:35 GMT+01:00 Matthias Zeis <notifications@github.com>:

**Comment by mopheus** [comment]
Bitte verwenden Sie unsere neue EMAIL Adresse : ifenthaler@net2sell.de

Danke

**Comment by mzeis** [comment]
I'll close this issue due to inactivity. If somebody wants to do the necessary re-factoring please feel be welcomed to create a PR. :-)
