### ISSUE TITLE
Fatal error when try to preview New Invoice mail

### ISSUE THREAD

**Issue by fredsvanelli** [magento-hackathon/E-MailPreview#17]
When I try to preview the "New Invoice" or "New shipment", I get the following error:

**Fatal error: Call to a member function getMethodInstance() on boolean in app/code/core/Mage/Payment/Helper/Data.php on line 119**

Any other previews works fine.

Magento 1.9.1.0

**Comment by mzeis** [comment]
Hi,

please can you specify which commit of the extension you are using and which data you entered? 

I tried to reproducte the problem with the `dev` branch. I had to fix a few things locally to get the extension working (not pushed yet), but then I could preview invoices and shipments.

**Comment by mzeis** [comment]
Closed due to inactivity. Please follow up with details and I will re-open the issue.
